package com.example.mybatisdemo.model;

public class Authorities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authorities.authority
     *
     * @mbg.generated
     */
    private String authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    public Authorities(String username, String authority) {
        this.username = username;
        this.authority = authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.username
     *
     * @return the value of authorities.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authorities.authority
     *
     * @return the value of authorities.authority
     *
     * @mbg.generated
     */
    public String getAuthority() {
        return authority;
    }
}