package com.example.mybatisdemo.mapper;

import com.example.mybatisdemo.model.Authorities;
import com.example.mybatisdemo.model.AuthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    long countByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    int deleteByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    int insertSelective(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    List<Authorities> selectByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);
}